### ISSUE TITLE
Setup for making contributions

### ISSUE THREAD

**Issue by maskaravivek** [videowikips/videowiki#1]
I came across this project and was hoping to make some minor contributions to it but according to the documentation, I am supposed to set up developer accounts on various sites such as slack, aws, mailgun etc. 

Can we have a common developer account at least for the staging environment?

Moreover, I tried running `npm run dev` and got the following error. I haven't setup any of the 3rd party accounts so this error could possibly be because of that. 

<img width="1353" alt="screen shot 2018-07-21 at 8 24 48 pm" src="https://user-images.githubusercontent.com/3069373/43036734-6ef8e8e6-8d24-11e8-9c88-562c59596712.png">

**Comment by hassanamin994** [comment]
Hello @maskaravivek 
Thank you for considering contributing to VideoWiki.

Regarding the 3rd party services that VideoWiki depends on, I'll be pushing  changes sometime this week removing the necessity to use Mailgun, Google Captcha and Slack ( they're not tightly bound to how VideoWiki works ). however please bear in mind that You'd need to add such accounts in case you want to use these parts in VideoWiki locally ( ex: Mailgun and Google Captcha for signing up )  

However regarding the main services used ( AWS Polly and S3 ), It'd be hard to give such test/development accounts as we're getting charged per character converted by AWS Polly and S3 storage, I'm currently implementing a solution for this issue ( provide default audios for articles when there's no AWS accounts used )

And regarding the issue you're having with `npm run dev` that's caused because your api is not running ( 
webpack server is configured to proxy over it ), make sure that the api is running before running the dev server.

**Comment by hassanamin994** [comment]
I've pushed new changes that will take care of the 3rd party services needed.
Now all you need to set up is APP_SECRET for express and DB_CONNECTION_URL for the mongodb instance.
